add_library(c_wwlib STATIC
    always.h
    argv.cpp
    argv.h
    b64pipe.cpp
    b64pipe.h
    b64straw.cpp
    b64straw.h
    base64.cpp
    base64.h
    #bfiofile.cpp
    #bfiofile.h
    binheap.h
    bittype.h
    bound.h
    bsearch.h
    buff.cpp
    buff.h
    bufffile.cpp
    bufffile.h
    callbackhook.h
    chunkio.cpp
    chunkio.h
    cpudetect.cpp
    cpudetect.h
    #crandom.h
    crc.cpp
    crc.h
    #crcpipe.cpp
    #crcpipe.h
    #crcstraw.cpp
    #crcstraw.h
    cstraw.cpp
    cstraw.h
    #Except.cpp
    #Except.h
    #FastAllocator.cpp
    #FastAllocator.h
    ffactory.cpp
    ffactory.h
    gcd_lcm.cpp
    gcd_lcm.h
    #global.h
    hash.cpp
    hash.h
    hashcalc.h
    hashlist.h
    #hashtab.h
    hashtemplate.h
    #incdec.h
    index.h
    ini.cpp
    ini.h
    inisup.h
    iostruct.h
    jshell.cpp
    listnode.h
    #lzo.cpp
    #lzo.h
    #lzo1x.h
    #lzo1x_c.cpp
    #lzo1x_d.cpp
    #lzoconf.h
    #lzopipe.cpp
    #lzopipe.h
    #lzostraw.cpp
    #lzostraw.h
    #lzo_conf.h
    #md5.cpp
    #md5.h
    mempool.h
    mmsys.h
    multilist.cpp
    multilist.h
    mutex.cpp
    mutex.h
    #noinit.h
    #notifier.h
    nstrdup.cpp
    nstrdup.h
    ntree.h
    pipe.cpp
    pipe.h
    point.h
    ramfile.cpp
    ramfile.h
    random.cpp
    random.h
    rawfile.cpp
    rawfile.h
    readline.cpp
    readline.h
    realcrc.cpp
    realcrc.h
    ref_ptr.h
    refcount.cpp
    refcount.h
    #regexpr.cpp
    #regexpr.h
    #search.h
    sharebuf.h
    signaler.h
    simplevec.h
    slist.h
    slnode.cpp
    slnode.h
    stimer.cpp
    stimer.h
    straw.cpp
    straw.h
    strtok_r.cpp
    strtok_r.h
    #swap.h
    systimer.cpp
    systimer.h
    targa.cpp
    targa.h
    textfile.cpp
    textfile.h
    #tgatodxt.cpp
    #tgatodxt.h
    thread.cpp
    thread.h
    trect.h
    trim.cpp
    trim.h
    uarray.h
    vector.cpp
    vector.h
    visualc.h
    widestring.cpp
    widestring.h
    win.h
    wwfile.cpp
    wwfile.h
    wwfont.cpp
    wwfont.h
    wwstring.cpp
    wwstring.h
    xpipe.cpp
    xpipe.h
    xstraw.cpp
    xstraw.h
)

### Target configuration
set_target_properties(c_wwlib PROPERTIES OUTPUT_NAME WWLib)
target_link_libraries(c_wwlib PUBLIC c_wwdebug_include c_libraries_include)
target_include_directories(c_wwlib PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
add_library(Common::WWLib ALIAS c_wwlib)