set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib/common)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/lib/common)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin/common)

include(Deps/dx8.cmake)
if(RTS_USE_LZHL)
    include(Deps/lzhl.cmake)
endif()
include(Deps/gamespy.cmake)

add_subdirectory(Compat)
add_subdirectory(Libraries)
add_subdirectory(Tools)
if (RTS_ENABLE_TESTS)
    add_subdirectory(Tests)
endif()